### ISSUE TITLE
What needs to happen to clear to make this a better plugin.

### ISSUE THREAD

**Issue by KingTux2** [Fedoracraft/Media-Plugin#1]
@ryandw11 This is what we need to do to get this plugin ready.
- [x] Make it better coded
- [ ] Comment the hell out of it
- [ ] Make sure it all 1.11 bugs are cleared
- [ ] Setup auto message about using /media
- [ ] Make the Gui look nicer!
- [ ] Write terms of use on this plugin code.

**Comment by ryandw11** [comment]
Fixed much of the coding.
